### ISSUE TITLE
Interop with another crash monitoring tools

### ISSUE THREAD

**Issue by jakoss** [skydoves/snitcher#2]
**Is your feature request related to a problem?**

While i love the idea of having the error screen for internal tests (like QA tests) - i still would like to have the same experience in the crashlytics console. Raporting exceptions using Crashlytics.logs is not reporting those as crashes, but rather as non-fatal issues. 

**Describe the solution you'd like:**

There is an API `Thread.getDefaultUncaughtExceptionHandler()` which gets currently set exception handler. You could try to intercept it before setting your exception handler and then try to call the original one.

There is an library which is doing that pretty nice, here's the code: https://github.com/pandulapeter/beagle/blob/master/log-crash/src/main/java/com/pandulapeter/beagle/logCrash/implementation/ExceptionHandler.kt

**Comment by skydoves** [comment]
The new version 1.0.1 has been released and it checks if the default thread handler is registered by Firebase. Thanks for reporting this great issue,  @jakoss!

**Comment by skydoves** [comment]
@jakoss I just realized you can also report exceptions by using `FirebaseCrashlytics.getInstance().recordException()` method.

**Comment by jakoss** [comment]
> @jakoss I just realized you can also report exceptions by using `FirebaseCrashlytics.getInstance().recordException()` method.

Yes, but those show up as a non-fatal issues on the dashboard. AFAIK there is no way to report as crash using public api
