### ISSUE TITLE
Display device and application information in ExceptionTraceActivity

### ISSUE THREAD

**Issue by jimlyas** [skydoves/snitcher#8]
**Is your feature request related to a problem?**

This is related to make informed decision about the exception. To know which device or which version of the application caused the exception.

**Describe the solution you'd like:**

The `ExceptionTraceActivity` can display information about the device and the installed application to help QA or the developer in having more information.

**Comment by skydoves** [comment]
Hey @jimlyas, thanks for raising this issue. That sounds very helpful to trace issues. Let me take this improvement for the next release. Thanks!

**Comment by skydoves** [comment]
Hey @jimlyas, 1.0.3 has been released and it displays application & device information on the `ExceptionTraceActivity`. Thanks for sharing your great idea!
